proveedores:
  - nombre: "Google Play"
    keywords_identificacion:
      - "Google Play"
      - "Play Store"
    rut_defecto: "EXTRANJERO"
    reglas:
      total: "regex: Total\\s*\\$?([\\d\\.]+)"
      fecha: "regex: del (\\d{1,2} [a-z]{3} \\d{4})"
